model_list:
  - model_name: phi4:latest
    litellm_params:
      model: ollama/phi4:latest
      api_base: http://192.168.10.11:11434

  - model_name: qwen2.5:32b-instruct-q4_K_M
    litellm_params:
      model: ollama/qwen2.5:32b-instruct-q4_K_M
      api_base: http://127.0.0.1:11435

  - model_name: qwen2.5:32b-instruct-q4_K_M
    litellm_params:
      model: ollama/qwen2.5:32b-instruct-q4_K_M
      api_base: http://127.0.0.1:11436

  - model_name: deepseek-coder-v2:33b-instruct-q4_K_M
    litellm_params:
      model: ollama/deepseek-coder-v2:33b-instruct-q4_K_M
      api_base: http://127.0.0.1:11437

general_settings:
  master_key: sk-llm-cluster
