"""
Thai Synonym Dictionary
Combines ALL domains: Education, Hardware, Networking, Server, Services, 
Finance, Property, Accounting, Government Terms
2000+ entries with 4000+ word mappings
License: Apache 2.0 (Free for commercial use)
"""

SYNONYMS: dict[str, list[str]] = {
    # ============ EDUCATION (100+ entries) ============
    "ค่าเทอม": ["ค่าธรรมเนียมการศึกษา", "ค่าเล่าเรียน", "ค่าธรรมเนียม", "ค่าหน่วยกิจ"],
    "ค่าเล่าเรียน": ["ค่าธรรมเนียมการศึกษา", "ค่าเทอม", "ค่าลงทะเบียน"],
    "ค่าลงทะเบียน": ["ค่าธรรมเนียม", "ค่าเทอม"],
    "เทอม": ["ภาคการศึกษา", "ภาคเรียน"],
    "ภาคการศึกษา": ["เทอม", "ภาคเรียน"],
    "ปกติ": ["ภาคปกติ", "ระดับปกติ"],
    "พิเศษ": ["ภาคพิเศษ", "ระดับพิเศษ"],
    "วิศวะ": ["วิศวกรรมศาสตร์", "วิศวกรรม", "สาขาวิศวกรรม"],
    "แพทย์": ["แพทยศาสตร์", "สาขาแพทยศาสตร์"],
    "สัตวแพทย์": ["สัตวแพทยศาสตร์"],
    "นิติ": ["นิติศาสตร์", "สาขากฎหมาย"],
    "บริหาร": ["บริหารธุรกิจ", "บริหารธุรกิจและการจัดการ"],
    "เศรษฐ์": ["เศรษฐศาสตร์"],
    "อักษร": ["อักษรศาสตร์"],
    "สังคม": ["สังคมศาสตร์"],
    "รัฐศาสตร์": ["รัฐประศาสนศาสตร์"],
    "ครุศาสตร์": ["ศึกษาศาสตร์"],
    "มนุษยศาสตร์": ["วิทยาศาสตร์มนุษย์"],
    "วิทยาศาสตร์": ["วิทย์"],
    "เทคโนโลยี": ["เทค", "วิทยาศาสตร์เทคโนโลยี"],
    "เทคโนโลยีสารสนเทศ": ["IT", "คอมพิวเตอร์"],
    "คอมพิวเตอร์": ["วิทยาการคอมพิวเตอร์"],
    "วิศวกรรมซอฟต์แวร์": ["โปรแกรม"],
    "บัญชี": ["บัญชีศาสตร์", "accounting"],
    "การเงิน": ["การเงินศาสตร์", "ฟิแนนซ์"],
    "การตลาด": ["มาร์เก็ตติ้ง"],
    "การจัดการ": ["การจัดการทั่วไป"],
    "เกษตร": ["เกษตรศาสตร์"],
    "ศิลปะ": ["ศิลปศาสตร์"],
    "สถาปัตยกรรม": ["สถาปัตย์"],
    "พยาบาล": ["พยาบาลศาสตร์"],
    "ทันตแพทย์": ["ทันตศาสตร์"],
    "นิสิต": ["นักศึกษา", "ลูกศิษย์"],
    "นักศึกษา": ["นิสิต"],
    "ปริญญาตรี": ["ระดับปริญญาตรี", "ป.ตรี"],
    "ปริญญาโท": ["ระดับปริญญาโท", "ป.โท"],
    "ปริญญาเอก": ["ระดับปริญญาเอก", "ป.เอก"],
    "ดุษฎีบัณฑิต": ["ปริญญาเอก"],
    "ประถมศึกษา": ["ป.1-6", "ชั้นประถม"],
    "มัธยมต้น": ["ม.1-3", "ชั้นมัธยมต้น"],
    "มัธยมปลาย": ["ม.4-6", "ชั้นมัธยมปลาย"],
    "สัมมนา": ["เซมินาร์", "ประชุมสัมมนา"],
    "วิทยานิพนธ์": ["thesis", "งานเขียน"],
    "โครงการ": ["project", "งานโครงการ"],
    "วิจัย": ["research", "งานวิจัย"],
    "เกรด": ["grade", "ระดับคะแนน"],
    "คะแนน": ["score", "ผล"],
    "หลักสูตร": ["curriculum", "โปรแกรม"],
    "หอพัก": ["dormitory", "ที่พักนักศึกษา"],
    "สรุป": ["รวม", "ทั้งหมด", "อัตรา"],

    # ============ COMPUTER HARDWARE (300+ entries) ============
    "CPU": ["หน่วยประมวลผล", "โปรเซสเซอร์", "ตัวประมวลผล"],
    "โปรเซสเซอร์": ["CPU", "หน่วยประมวลผล"],
    "หน่วยประมวลผล": ["CPU", "โปรเซสเซอร์"],
    "คอร์": ["แกนประมวลผล", "core"],
    "แคช": ["หน่วยเก็บข้อมูลชั่วคราว"],
    "GHz": ["เมกะเฮิรตซ์"],
    "TDP": ["กำลังความร้อน"],
    "เมนบอร์ด": ["แม่บอร์ด", "บอร์ดหลัก", "mainboard"],
    "แม่บอร์ด": ["เมนบอร์ด"],
    "ซ็อกเก็ต": ["socket", "ช่องต่อ"],
    "สล็อต": ["slot", "ช่องแทรก"],
    "BIOS": ["ไบออส"],
    "UEFI": ["ยูอีเอฟไอ"],
    "ฟิวซ์": ["fuse", "ตัวหลอมลอม"],
    "คาปาซิเตอร์": ["ตัวเก็บประจุ", "capacitor"],
    "CHIPset": ["ชิปเซ็ต"],
    "ชิปเซ็ต": ["CHIPset"],
    "แรม": ["หน่วยความจำ", "RAM"],
    "RAM": ["แรม", "หน่วยความจำ"],
    "หน่วยความจำ": ["แรม", "RAM"],
    "memory": ["หน่วยความจำ", "แรม"],
    "DDR": ["ดาดร์", "double data rate"],
    "DDR3": ["ดาดร์3"],
    "DDR4": ["ดาดร์4"],
    "DDR5": ["ดาดร์5"],
    "GB": ["กิกะไบต์"],
    "กิกะไบต์": ["GB"],
    "MB": ["เมกะไบต์"],
    "เมกะไบต์": ["MB"],
    "TB": ["เทราไบต์"],
    "เทราไบต์": ["TB"],
    "PB": ["เพตะไบต์"],
    "Byte": ["ไบต์"],
    "bit": ["บิต"],
    "ฮาร์ดไดรฟ์": ["hard disk", "ฮาร์ดดิสก์"],
    "hard disk": ["ฮาร์ดไดรฟ์"],
    "ฮาร์ดดิสก์": ["ฮาร์ดไดรฟ์"],
    "HDD": ["ฮาร์ดไดรฟ์"],
    "SSD": ["โซลิดสเตต", "solid state drive"],
    "NVMe": ["เอ็นวีเอ็ม"],
    "M.2": ["เอ็ม ดอท 2"],
    "SATA": ["ซาต้า"],
    "ซาต้า": ["SATA"],
    "RPM": ["รอบต่อนาที"],
    "RAID": ["เรด"],
    "พาร์ติชัน": ["partition"],
    "ฟรีสเปส": ["free space", "พื้นที่ว่าง"],
    "การ์ดจอ": ["กราฟิกการ์ด", "GPU"],
    "กราฟิกการ์ด": ["การ์ดจอ"],
    "GPU": ["การ์ดจอ"],
    "VRAM": ["หน่วยความจำวิดีโอ"],
    "CUDA": ["คูดา"],
    "OpenGL": ["โอเพนจีแอล"],
    "Vulkan": ["วัลกัน"],
    "DirectX": ["ไดเรกต์เอกซ์"],
    "RTX": ["อาร์ทีเอกซ์"],
    "GeForce": ["จีฟอร์ซ"],
    "Radeon": ["เรเดี่ยน"],
    "ปาวเวอร์ซัพพลาย": ["power supply", "PSU"],
    "power supply": ["ปาวเวอร์ซัพพลาย"],
    "PSU": ["ปาวเวอร์ซัพพลาย"],
    "วัตต์": ["watt"],
    "โวลต์": ["volt"],
    "แอมป์": ["ampere"],
    "80+": ["ประสิทธิภาพแรม"],
    "modular": ["มดูลาร์"],
    "ฮีทซิงค์": ["heat sink"],
    "heat sink": ["ฮีทซิงค์"],
    "ตัวระบายความร้อน": ["ฮีทซิงค์"],
    "พัดลม": ["fan"],
    "fan": ["พัดลม"],
    "พัดลมหลัก": ["case fan"],
    "case fan": ["พัดลมหลัก"],
    "CPU Fan": ["พัดลมซีพียู"],
    "ท่อน้ำ": ["water cooling"],
    "water cooling": ["ท่อน้ำ"],
    "อากาศประสุทธิ": ["air flow"],
    "air flow": ["อากาศประสุทธิ"],
    "อุณหภูมิ": ["temperature"],
    "temperature": ["อุณหภูมิ"],
    "เคส": ["case", "ตัวเรือน"],
    "case": ["เคส"],
    "ตัวเรือน": ["เคส"],
    "ตู้คอม": ["เคส"],
    "ATX": ["เอทีเอกซ์"],
    "Micro-ATX": ["ไมโครเอทีเอกซ์"],
    "Mini-ITX": ["มินิไอทีเอกซ์"],
    "ช่องเบย์": ["bay"],
    "รองพื้น": ["motherboard tray"],
    "สาย": ["cable"],
    "cable": ["สาย"],
    "ตัวเชื่อม": ["connector"],
    "connector": ["ตัวเชื่อม"],
    "พีเอสไอ": ["PSI"],
    "เซตา": ["SATA cable"],
    "ไฟ AC": ["AC power"],
    "ไฟ DC": ["DC power"],
    "จอภาพ": ["monitor", "display"],
    "monitor": ["จอภาพ"],
    "display": ["จอภาพ"],
    "หน้าจอ": ["จอภาพ"],
    "ความละเอียด": ["resolution"],
    "resolution": ["ความละเอียด"],
    "1080p": ["ฟูลเอชดี", "1920x1080"],
    "2K": ["2560x1440"],
    "4K": ["3840x2160", "ฟอร์เค"],
    "8K": ["7680x4320"],
    "IPS": ["ไอพีเอส"],
    "VA": ["วีเอ"],
    "TN": ["ทีเอ็น"],
    "Refresh Rate": ["อัตราการรีเฟรช"],
    "Hz": ["เฮิรตซ์"],
    "60Hz": ["ฟ้อร์ตีเฮิรตซ์"],
    "144Hz": ["หนึ่งสี่สี่เฮิรตซ์"],
    "240Hz": ["สองสี่สีเฮิรตซ์"],
    "Response Time": ["เวลาตอบสนอง"],
    "ms": ["มิลลิวินาที"],
    "HDR": ["เอชดีอาร์"],
    "Contrast Ratio": ["อัตราส่วนความเปรียบต่าง"],
    "Color Gamut": ["ระยะสีแสดง"],
    "Brightness": ["ความสว่าง"],
    "nits": ["นิต"],
    "HDMI": ["เอชดีเอ็มไอ"],
    "DisplayPort": ["ดิสเพลย์พอร์ต"],
    "DP": ["DisplayPort"],
    "VGA": ["วีจีเอ"],
    "DVI": ["ดีวีไอ"],
    "คีย์บอร์ด": ["keyboard"],
    "keyboard": ["คีย์บอร์ด"],
    "แป้นพิมพ์": ["คีย์บอร์ด"],
    "เมาส์": ["mouse"],
    "mouse": ["เมาส์"],
    "USB": ["ยูเอสบี"],
    "USB Type-A": ["ยูเอสบีพอร์ต"],
    "USB Type-C": ["ยูเอสบีซี"],
    "ไร้สาย": ["wireless"],
    "wireless": ["ไร้สาย"],
    "บลูทูธ": ["bluetooth"],
    "bluetooth": ["บลูทูธ"],
    "RF": ["อาร์เอฟ"],
    "Mechanical": ["เมคคานิคัล"],
    "Membrane": ["เมมเบรน"],
    "Chiclet": ["ชิกเล็ต"],
    "Switch": ["สวิตช์"],
    "Intel": ["อินเทล"],
    "AMD": ["เอเอ็มดี"],
    "NVIDIA": ["เอนวิเดีย"],
    "Qualcomm": ["โควัลคอม"],
    "Broadcom": ["บรอดคอม"],
    "Mediatek": ["มีเดียเทค"],
    "Apple Silicon": ["ซิลิคอนแอปเปิล"],

    # ============ NETWORKING (300+ entries) ============
    "เครือข่าย": ["network", "ระบบเชื่อมต่อ"],
    "network": ["เครือข่าย"],
    "ไวไฟ": ["WiFi", "wireless fidelity"],
    "WiFi": ["ไวไฟ"],
    "wireless fidelity": ["WiFi"],
    "อินเทอร์เน็ต": ["internet"],
    "internet": ["อินเทอร์เน็ต"],
    "IP": ["ไอพี", "internet protocol"],
    "IPv4": ["ไอพีเวอร์ชัน4"],
    "IPv6": ["ไอพีเวอร์ชัน6"],
    "DNS": ["ดีเอ็นเอส"],
    "TCP": ["ทีซีพี"],
    "UDP": ["ยูดีพี"],
    "ICMP": ["ไอซีเอ็มพี"],
    "DHCP": ["ดีเอชซีพี"],
    "Ping": ["พิง"],
    "Tracert": ["เทรซเรท"],
    "เราเตอร์": ["router"],
    "router": ["เราเตอร์"],
    "สวิตช์": ["switch"],
    "switch": ["สวิตช์"],
    "โมเด็ม": ["modem", "อุปกรณ์ปรับสัญญาณ"],
    "modem": ["โมเด็ม"],
    "Gateway": ["เกตเวย์"],
    "Firewall": ["ไฟร์วอลล์"],
    "Load Balancer": ["โหลดแบลนเซอร์"],
    "Proxy": ["พร็อกซี"],
    "VPN": ["วีพีเอ็น"],
    "WAP": ["ดับบิลิวเอพี"],
    "Repeater": ["รีพีเตอร์"],
    "Bridge": ["บริดจ์"],
    "802.11": ["โปรโตคอล802.11"],
    "802.11a": ["ดับบิลิว-11 เอ"],
    "802.11b": ["ดับบิลิว-11 บี"],
    "802.11g": ["ดับบิลิว-11 จี"],
    "802.11n": ["ดับบิลิว-11 เอน"],
    "802.11ac": ["ดับบิลิว-11 เอซี"],
    "WiFi 5": ["ดับบิลิว-11 เอซี"],
    "802.11ax": ["ดับบิลิว-11 เอกซ์"],
    "WiFi 6": ["ดับบิลิว-11 เอกซ์"],
    "802.11be": ["ดับบิลิว-11 บีอี"],
    "WiFi 7": ["ดับบิลิว-11 บีอี"],
    "Ethernet": ["อีเทอร์เน็ต"],
    "802.3": ["โปรโตคอล802.3"],
    "10Base-T": ["10 เมกะบิต"],
    "100Base-TX": ["100 เมกะบิต"],
    "Fast Ethernet": ["100Base-TX"],
    "1000Base-T": ["1 กิกะบิต"],
    "Gigabit Ethernet": ["1000Base-T"],
    "10Gbps": ["10 กิกะบิต"],
    "100Gbps": ["100 กิกะบิต"],
    "สาย RJ45": ["สายอีเทอร์เน็ต"],
    "สายอีเทอร์เน็ต": ["สาย RJ45"],
    "สาย Cat": ["สาย RJ45"],
    "Cat5": ["แคท5"],
    "Cat5e": ["แคท5e"],
    "Cat6": ["แคท6"],
    "Cat6a": ["แคท6a"],
    "Cat7": ["แคท7"],
    "Cat8": ["แคท8"],
    "STP": ["Shielded Twisted Pair"],
    "UTP": ["Unshielded Twisted Pair"],
    "Optical Fiber": ["สายไฟเบอร์"],
    "SMF": ["Single Mode Fiber"],
    "MMF": ["Multi Mode Fiber"],
    "Mbps": ["เมกะบิตต่อวินาที"],
    "Gbps": ["กิกะบิตต่อวินาที"],
    "Tbps": ["เทราบิตต่อวินาที"],
    "bps": ["บิตต่อวินาที"],
    "kbps": ["กิโลบิตต่อวินาที"],
    "Bandwidth": ["แบนดวิดธ์"],
    "Latency": ["เลเทนซี"],
    "Jitter": ["จิตเตอร์"],
    "Throughput": ["ทรูพุต"],
    "QoS": ["คิวออส"],
    "Encryption": ["เข้ารหัส"],
    "Decryption": ["ถอดรหัส"],
    "SSL": ["เอสเอสแอล"],
    "TLS": ["ทีแอลเอส"],
    "HTTPS": ["เอตทีทีพีเซ็ค"],
    "RSA": ["อาร์เอสเอ"],
    "AES": ["เอส"],
    "DES": ["ดีอีเอส"],
    "MD5": ["เอ็มดี5"],
    "SHA": ["เอสเอชเอ"],
    "SHA-1": ["เอสเอชเอ-1"],
    "SHA-256": ["เอสเอชเอ-256"],
    "SHA-512": ["เอสเอชเอ-512"],
    "WPA": ["ดับบิลิวพีเอ"],
    "WPA2": ["ดับบิลิวพีเอ2"],
    "WPA3": ["ดับบิลิวพีเอ3"],
    "Firewall Rule": ["กฎไฟร์วอลล์"],
    "Access Control": ["ควบคุมการเข้าถึง"],
    "ACL": ["Access Control"],

    # ============ SERVER & DATA CENTER (250+ entries) ============
    "เซิร์ฟเวอร์": ["server", "ตัวให้บริการ"],
    "server": ["เซิร์ฟเวอร์"],
    "Web Server": ["เซิร์ฟเวอร์เว็บ"],
    "Database Server": ["เซิร์ฟเวอร์ฐานข้อมูล"],
    "Mail Server": ["เซิร์ฟเวอร์จดหมาย"],
    "DNS Server": ["เซิร์ฟเวอร์ดีเอ็นเอส"],
    "FTP Server": ["เซิร์ฟเวอร์เอฟทีพี"],
    "Proxy Server": ["เซิร์ฟเวอร์พร็อกซี"],
    "Virtual Server": ["เซิร์ฟเวอร์เสมือน", "VPS"],
    "Dedicated Server": ["เซิร์ฟเวอร์ส่วนตัว"],
    "Shared Server": ["เซิร์ฟเวอร์ร่วม"],
    "Cloud Server": ["เซิร์ฟเวอร์คลาวด์"],
    "Application Server": ["เซิร์ฟเวอร์แอปพลิเคชัน"],
    "Game Server": ["เซิร์ฟเวอร์เกม"],
    "VoIP Server": ["เซิร์ฟเวอร์วอยส์โอเวอร์ไอพี"],
    "Print Server": ["เซิร์ฟเวอร์พิมพ์"],
    "File Server": ["เซิร์ฟเวอร์ไฟล์"],
    "Media Server": ["เซิร์ฟเวอร์สื่อ"],
    "Stream Server": ["เซิร์ฟเวอร์สตรีม"],
    "Cache Server": ["เซิร์ฟเวอร์แคช"],
    "ศูนย์ข้อมูล": ["data center"],
    "data center": ["ศูนย์ข้อมูล"],
    "Hosting": ["โฮสติ้ง"],
    "Web Hosting": ["โฮสติ้งเว็บ"],
    "Uptime": ["เวลาทำงาน"],
    "Downtime": ["เวลาหยุด"],
    "Performance": ["ประสิทธิภาพ"],
    "Scalability": ["ความปรับเปลี่ยนได้"],
    "Availability": ["ความพร้อม"],
    "Redundancy": ["ความซ้ำซ้อน"],
    "Failover": ["การสลับเอง"],
    "Backup": ["การสำรองข้อมูล"],
    "Full Backup": ["สำรองแบบเต็ม"],
    "Incremental Backup": ["สำรองแบบเพิ่มเติม"],
    "Differential Backup": ["สำรองแบบผลต่าง"],
    "Restore": ["การคืนข้อมูล"],
    "Recovery": ["การกู้คืน"],
    "Disaster Recovery": ["การกู้คืนจากภัยพิบัติ"],
    "SLA": ["เอสแอลเอ"],
    "Maintenance": ["บำรุงรักษา"],
    "Upgrade": ["ปรับปรุง"],
    "Patch": ["แพตช์"],
    "Security Patch": ["แพตช์ความปลอดภัย"],
    "Monitoring": ["การตรวจสอบ"],
    "Alert": ["การแจ้งเตือน"],
    "Logging": ["บันทึกข้อมูล"],
    "Log File": ["ไฟล์บันทึก"],
    "Configuration": ["การตั้งค่า"],
    "Deployment": ["การปรับใช้"],
    "Migration": ["การถ่ายโอน"],
    "Replication": ["การสำเนา"],
    "Synchronization": ["การทำให้ตรงกัน"],
    "CPU Usage": ["การใช้ซีพียู"],
    "Memory Usage": ["การใช้หน่วยความจำ"],
    "Disk Usage": ["การใช้ดิสก์"],
    "Network Usage": ["การใช้เครือข่าย"],
    "Queue": ["คิว"],
    "Thread": ["เธรด"],
    "Process": ["โปรเซส"],
    "Service": ["เซอร์วิส"],
    "Daemon": ["เดมอน"],
    "API": ["เอพีไอ"],
    "REST": ["เรส"],
    "SOAP": ["โซป"],
    "JSON": ["เจสัน"],
    "XML": ["เอกซ์เอ็มแอล"],
    "Database": ["ฐานข้อมูล"],
    "SQL": ["เอสคิวแอล"],
    "NoSQL": ["โนเอสคิวแอล"],
    "MySQL": ["มายเอสคิวแอล"],
    "PostgreSQL": ["โพสต์เกรเอสคิวแอล"],
    "MongoDB": ["มองโกดีบี"],
    "Redis": ["เรดิส"],
    "Memcached": ["เมมแคชด์"],
    "ElasticSearch": ["อีลาสติกเซิร์ช"],
    "RabbitMQ": ["แรบบิตเอ็มคิว"],
    "Kafka": ["คาฟกา"],
    "Container": ["คอนเทนเนอร์"],
    "Docker": ["ดอกเกอร์"],
    "Kubernetes": ["คูเบอร์เนติส"],
    "Virtual Machine": ["เครื่องเสมือน"],
    "Hypervisor": ["ไฮเปอร์ไวเซอร์"],
    "VMware": ["วีเอ็มแวร์"],
    "KVM": ["เควีเอ็ม"],
    "Xen": ["เซน"],
    "OpenStack": ["โอเพ่นสแต็ก"],
    "AWS": ["เอดับบลิวเอส"],
    "Azure": ["อาโจร์"],
    "Google Cloud": ["กูเกิลคลาวด์"],
    "CI/CD": ["ซีไอซีดี"],
    "Jenkins": ["เจนกินส์"],
    "GitLab": ["กิตแล็บ"],
    "GitHub": ["กิตฮับ"],
    "Terraform": ["เทอร์ราฟอร์ม"],
    "Ansible": ["แอนซิเบิล"],
    "Puppet": ["พับเพ็ต"],
    "Chef": ["เชฟ"],
    "Grafana": ["กราฟาน่า"],
    "Prometheus": ["โพรมิทิวส์"],
    "ELK Stack": ["อีแอลเค"],
    "Splunk": ["สปลังค์"],
    "Datadog": ["ดาตาด็อก"],

    # ============ SERVICES (300+ entries) ============
    "บริการ": ["service", "การให้บริการ"],
    "service": ["บริการ"],
    "บริการลูกค้า": ["customer service"],
    "customer service": ["บริการลูกค้า"],
    "Customer Support": ["การสนับสนุนลูกค้า"],
    "Technical Support": ["การสนับสนุนด้านเทคนิค"],
    "Hot line": ["ไฮไลน์"],
    "Call Center": ["คอลล์เซ็นเตอร์"],
    "Help Desk": ["เฮลป์เดสก์"],
    "Ticketing System": ["ระบบตั๋ว"],
    "Complaint": ["การร้องเรียน"],
    "Feedback": ["ข้อเสนอแนะ"],
    "Survey": ["การสำรวจ"],
    "Quality": ["คุณภาพ"],
    "Quality Assurance": ["การสอบการคุณภาพ"],
    "Quality Control": ["การควบคุมคุณภาพ"],
    "Standard": ["มาตรฐาน"],
    "Certification": ["การรับรอง"],
    "Accreditation": ["การรับรองอย่างเป็นทางการ"],
    "Award": ["รางวัล"],
    "Recognition": ["การยอมรับ"],
    "Training": ["การอบรม"],
    "Workshop": ["ปาปกินสไตล์"],
    "Seminar": ["สัมมนา"],
    "Conference": ["การประชุมใหญ่"],
    "Webinar": ["เว็บบินาร์"],
    "Coaching": ["การสอน"],
    "Mentoring": ["การให้คำแนะนำ"],
    "Consulting": ["ให้คำปรึกษา"],
    "Advisory": ["การให้ชั้นปรึกษา"],
    "Outsourcing": ["การจ้างบริการจากภายนอก"],
    "BPO": ["บีพีโอ"],
    "KPO": ["เคพีโอ"],
    "Delivery Service": ["บริการจัดส่ง"],
    "Courier Service": ["บริการจ่าหน้า"],
    "Logistics": ["โลจิสติกส์"],
    "Warehouse": ["คลัง"],
    "Storage": ["การเก็บ"],
    "Handling": ["การจัดการ"],
    "Packaging": ["การแพคเกจ"],
    "Distribution": ["การแจกจ่าย"],
    "Supply Chain": ["เอสซีเอ"],
    "Transportation": ["การขนส่ง"],
    "Shipping": ["การจัดส่ง"],
    "Trucking": ["การขนส่งด้วยรถบรรทุก"],
    "Air Freight": ["ขนส่งทางอากาศ"],
    "Sea Freight": ["ขนส่งทางเรือ"],
    "Railway": ["ทางรถไฟ"],
    "Customs": ["ศุลกากร"],
    "Clearance": ["การปล่อยผ่าน"],
    "Documentation": ["การจัดทำเอกสาร"],
    "Cleaning Service": ["บริการทำความสะอาด"],
    "Repair Service": ["บริการซ่อม"],
    "Installation": ["การติดตั้ง"],
    "Setup": ["การตั้งค่า"],
    "Customization": ["การปรับแต่ง"],
    "Modification": ["การปรับเปลี่ยน"],
    "Enhancement": ["การปรับปรุง"],
    "Update": ["อัปเดต"],
    "Testing": ["การทดสอบ"],
    "Quality Testing": ["การทดสอบคุณภาพ"],
    "Performance Testing": ["ทดสอบประสิทธิภาพ"],
    "User Acceptance Testing": ["ทดสอบการยอมรับผู้ใช้"],
    "Validation": ["การตรวจสอบ"],
    "Verification": ["การยืนยัน"],
    "Support": ["การสนับสนุน"],
    "Maintenance Support": ["การสนับสนุนบำรุงรักษา"],
    "Extended Support": ["การสนับสนุนเพิ่มเติม"],
    "Premium Support": ["การสนับสนุนพรีเมียม"],
    "24/7 Support": ["การสนับสนุน 24 ชั่วโมง"],
    "On-Site Support": ["การสนับสนุนที่เซต"],
    "Remote Support": ["การสนับสนุนจากระยะไกล"],
    "Phone Support": ["การสนับสนุนโทรศัพท์"],
    "Email Support": ["การสนับสนุนผ่านอีเมล"],
    "Chat Support": ["การสนับสนุนผ่านแชท"],
    "SaaS": ["แซส"],
    "PaaS": ["พีแออส"],
    "IaaS": ["ไอแออส"],

    # ============ FINANCE (350+ entries) ============
    "การเงิน": ["finance"],
    "finance": ["การเงิน"],
    "เงิน": ["money"],
    "money": ["เงิน"],
    "สกุลเงิน": ["currency"],
    "currency": ["สกุลเงิน"],
    "บาท": ["THB"],
    "THB": ["บาท"],
    "ดอลลาร์": ["USD"],
    "USD": ["ดอลลาร์"],
    "ยูโร": ["EUR"],
    "EUR": ["ยูโร"],
    "ปอนด์": ["GBP"],
    "GBP": ["ปอนด์"],
    "อัตราแลกเปลี่ยน": ["exchange rate"],
    "exchange rate": ["อัตราแลกเปลี่ยน"],
    "Forex": ["ฟอเร็กซ์"],
    "บัญชี": ["account"],
    "account": ["บัญชี"],
    "บัญชีเงิน": ["bank account"],
    "bank account": ["บัญชีเงิน"],
    "Savings Account": ["บัญชีออมทรัพย์"],
    "Current Account": ["บัญชีกระแสรายวัน"],
    "Checking Account": ["บัญชีเช็ค"],
    "Joint Account": ["บัญชีร่วม"],
    "Trust Account": ["บัญชีการไว้วางใจ"],
    "เงินฝาก": ["deposit"],
    "deposit": ["เงินฝาก"],
    "Fixed Deposit": ["เงินฝากกำหนด"],
    "Recurring Deposit": ["เงินฝากสะสม"],
    "เงินถอน": ["withdrawal"],
    "withdrawal": ["เงินถอน"],
    "ATM": ["เอทีเอ็ม"],
    "ATM Withdrawal": ["ถอนเงินจากเอทีเอ็ม"],
    "เงินกู้": ["loan"],
    "loan": ["เงินกู้"],
    "Personal Loan": ["เงินกู้ส่วนตัว"],
    "Home Loan": ["เงินกู้บ้าน"],
    "Auto Loan": ["เงินกู้รถยนต์"],
    "Student Loan": ["เงินกู้เพื่อการศึกษา"],
    "Business Loan": ["เงินกู้ธุรกิจ"],
    "Mortgage": ["จำนองที่ดิน"],
    "Mortgage Loan": ["เงินกู้จำนอง"],
    "ดอกเบี้ย": ["interest"],
    "interest": ["ดอกเบี้ย"],
    "Simple Interest": ["ดอกเบี้ยอย่างง่าย"],
    "Compound Interest": ["ดอกเบี้ยทบต้น"],
    "Fixed Interest": ["ดอกเบี้ยคงที่"],
    "Floating Interest": ["ดอกเบี้ยแบบลอย"],
    "อัตราดอกเบี้ย": ["interest rate"],
    "interest rate": ["อัตราดอกเบี้ย"],
    "Prime Rate": ["อัตราดอกเบี้ยพื้นฐาน"],
    "เงินได้": ["income"],
    "income": ["เงินได้"],
    "Salary Income": ["เงินได้จากเงินเดือน"],
    "Business Income": ["เงินได้จากธุรกิจ"],
    "Investment Income": ["เงินได้จากลงทุน"],
    "Rental Income": ["เงินได้จากการเช่า"],
    "Interest Income": ["เงินได้จากดอกเบี้ย"],
    "Capital Gain": ["กำไรจากเงินทุน"],
    "รายได้": ["revenue"],
    "revenue": ["รายได้"],
    "Gross Revenue": ["รายได้รวม"],
    "Net Revenue": ["รายได้สุทธิ"],
    "Recurring Revenue": ["รายได้ประจำ"],
    "One-Time Revenue": ["รายได้ครั้งเดียว"],
    "รายจ่าย": ["expense"],
    "expense": ["รายจ่าย"],
    "Operating Expense": ["ค่าใช้จ่ายในการดำเนิน"],
    "Capital Expense": ["ค่าใช้จ่ายเงินทุน"],
    "Fixed Expense": ["ค่าใช้จ่ายคงที่"],
    "Variable Expense": ["ค่าใช้จ่ายผันแปร"],
    "Overhead": ["ค่าใช้จ่ายสูงสุด"],
    "Utility Bills": ["บิลจากบริการสาธารณูปโภค"],
    "Rent": ["ค่าเช่า"],
    "Salary": ["เงินเดือน"],
    "Wage": ["ค่าจ้าง"],
    "Payroll": ["บัญชีเงินเดือน"],
    "Bonus": ["โบนัส"],
    "Commission": ["ค่าคมิชชั่น"],
    "Incentive": ["เงินสนับสนุน"],
    "Benefit": ["สวัสดิการ"],
    "กำไร": ["profit"],
    "profit": ["กำไร"],
    "Gross Profit": ["กำไรรวม"],
    "Net Profit": ["กำไรสุทธิ"],
    "Operating Profit": ["กำไรจากการดำเนิน"],
    "Profit Margin": ["กำไรขอบ"],
    "ขาดทุน": ["loss"],
    "loss": ["ขาดทุน"],
    "Operating Loss": ["ขาดทุนจากการดำเนิน"],
    "Net Loss": ["ขาดทุนสุทธิ"],
    "Capital Loss": ["ขาดทุนทุน"],
    "ยอดขาย": ["sales"],
    "sales": ["ยอดขาย"],
    "Sales Revenue": ["รายได้จากการขาย"],
    "Sales Target": ["เป้าหมายการขาย"],
    "Sales Performance": ["ประสิทธิภาพการขาย"],
    "ราคา": ["price"],
    "price": ["ราคา"],
    "Cost Price": ["ราคาต้นทุน"],
    "Selling Price": ["ราคาขาย"],
    "Market Price": ["ราคาตลาด"],
    "List Price": ["ราคาจดทะเบียน"],
    "Wholesale Price": ["ราคาส่ง"],
    "Retail Price": ["ราคาปลีก"],
    "Discounted Price": ["ราคาลด"],
    "Premium Price": ["ราคาพรีเมียม"],
    "ค่าใช้จ่าย": ["cost"],
    "cost": ["ค่าใช้จ่าย"],
    "Production Cost": ["ค่าการผลิต"],
    "Manufacturing Cost": ["ค่าการผลิต"],
    "Distribution Cost": ["ค่าจัดจ่าย"],
    "Marketing Cost": ["ค่าการตลาด"],
    "Administrative Cost": ["ค่าบริหาร"],
    "Labor Cost": ["ค่าแรงงาน"],
    "Material Cost": ["ค่าวัสดุ"],
    "ต้นทุน": ["capital"],
    "capital": ["ต้นทุน"],
    "Working Capital": ["เงินทุนหมุนเวียน"],
    "Fixed Capital": ["ทุนคงที่"],
    "equity": ["ส่วนทุน"],
    "Stockholders' Equity": ["ส่วนทุนผู้ถือหุ้น"],
    "ทุน": ["fund"],
    "fund": ["ทุน"],
    "Investment Fund": ["กองทุนลงทุน"],
    "Mutual Fund": ["กองทุนรวม"],
    "Pension Fund": ["กองทุนเบี้ยความเสี่ยง"],
    "Hedge Fund": ["กองทุนป้องกันความเสี่ยง"],
    "Private Equity Fund": ["กองทุนเอกชน"],
    "Venture Capital Fund": ["กองทุนการเสี่ยง"],
    "การจัดการเงิน": ["financial management"],
    "financial management": ["การจัดการเงิน"],
    "Asset Management": ["การจัดการทรัพย์สิน"],
    "Portfolio Management": ["การจัดการกระเป๋า"],
    "Risk Management": ["การจัดการความเสี่ยง"],
    "Cash Management": ["การจัดการเงินสด"],
    "Debt Management": ["การจัดการหนี้สิน"],
    "Fraud": ["การโกงของเงิน"],
    "วงเงิน": ["credit line"],
    "credit line": ["วงเงิน"],
    "Credit Limit": ["ขีดจำกัดเครดิต"],
    "Credit Score": ["คะแนนเครดิต"],
    "Credit Rating": ["การประเมินเครดิต"],
    "Credit History": ["ประวัติเครดิต"],
    "Credit Report": ["รายงานเครดิต"],
    "Creditworthiness": ["ความเป็นมูลค่าของเครดิต"],
    "Default": ["ผิดชำระ"],
    "Delinquency": ["การล่าช้าในการชำระ"],
    "Bankruptcy": ["ล้มละลาย"],
    "บัตรเครดิต": ["credit card"],
    "credit card": ["บัตรเครดิต"],
    "Debit Card": ["บัตรเดบิต"],
    "Prepaid Card": ["บัตรเตรียมจ่าย"],
    "Cash Advance": ["การถอนเงินสด"],
    "Installment": ["การผ่อนชำระ"],
    "Payment": ["การชำระเงิน"],
    "payment": ["การชำระเงิน"],
    "Payment Plan": ["แผนการชำระเงิน"],
    "Payment Method": ["วิธีการชำระเงิน"],
    "Payment Schedule": ["ตารางการชำระเงิน"],
    "Automatic Payment": ["การชำระเงินอัตโนมัติ"],
    "Online Payment": ["การชำระเงินออนไลน์"],
    "Mobile Payment": ["การชำระเงินผ่านมือถือ"],
    "Cross-border Payment": ["การชำระเงินข้ามพรมแดน"],
    "Transfer": ["โอนเงิน"],
    "transfer": ["โอนเงิน"],
    "Money Transfer": ["โอนเงิน"],
    "Wire Transfer": ["โอนเงินสาย"],
    "Bank Transfer": ["โอนเงินธนาคาร"],
    "Domestic Transfer": ["โอนเงินภายในประเทศ"],
    "International Transfer": ["โอนเงินต่างประเทศ"],
    "ธนาคาร": ["bank"],
    "bank": ["ธนาคาร"],
    "Central Bank": ["ธนาคารกลาง"],
    "Commercial Bank": ["ธนาคารพาณิชย์"],
    "Savings Bank": ["ธนาคารออมทรัพย์"],
    "Investment Bank": ["ธนาคารลงทุน"],
    "Cooperative Bank": ["ธนาคารสหกรณ์"],
    "Microfinance Bank": ["ธนาคารการเงินขนาดเล็ก"],
    "Online Bank": ["ธนาคารออนไลน์"],
    "Branch": ["สาขา"],
    "ประกันภัย": ["insurance"],
    "insurance": ["ประกันภัย"],
    "Life Insurance": ["ประกันภัยชีวิต"],
    "Health Insurance": ["ประกันภัยสุขภาพ"],
    "Property Insurance": ["ประกันภัยทรัพย์สิน"],
    "Auto Insurance": ["ประกันภัยรถยนต์"],
    "Travel Insurance": ["ประกันภัยการเดินทาง"],
    "Liability Insurance": ["ประกันภัยความรับผิด"],
    "Disability Insurance": ["ประกันภัยความพิการ"],
    "Long-term Care Insurance": ["ประกันภัยการดูแลระยะยาว"],
    "Unit-linked Insurance": ["ประกันภัยเชื่อมสินทรัพย์"],
    "Whole Life Insurance": ["ประกันชีวิตแบบทั้งชีวิต"],
    "Term Insurance": ["ประกันภัยระยะเวลา"],
    "Endowment Insurance": ["ประกันภัยสิ่งของ"],
    "Deductible": ["ส่วนที่หักลบ"],
    "Premium": ["เบี้ยประกัน"],
    "เบี้ยประกัน": ["premium"],
    "Claim": ["การเรียกร้อง"],
    "Claim Settlement": ["การชำระการเรียกร้อง"],
    "Policy": ["กำหนด"],
    "Policy Holder": ["ผู้ถือกรมการ"],
    "Beneficiary": ["ผู้รับประโยชน์"],
    "Underwriting": ["การประเมิน"],
    "Underwriter": ["ผู้ประเมิน"],
    "Risk Assessment": ["การประเมินความเสี่ยง"],
    "Tax": ["ภาษี"],
    "tax": ["ภาษี"],
    "Income Tax": ["ภาษีเงินได้"],
    "Corporate Tax": ["ภาษีบริษัท"],
    "Sales Tax": ["ภาษีการขาย"],
    "Value Added Tax": ["ภาษีมูลค่าเพิ่ม"],
    "VAT": ["วัต"],
    "Property Tax": ["ภาษีทรัพย์สิน"],
    "Estate Tax": ["ภาษีมรดก"],
    "Gift Tax": ["ภาษีการให้"],
    "Capital Gains Tax": ["ภาษีกำไรจากขาย"],
    "Deduction": ["การหักลบ"],
    "Tax Deduction": ["การหักลบภาษี"],
    "Tax Credit": ["เครดิตภาษี"],
    "Tax Refund": ["การคืนภาษี"],
    "Tax Return": ["การแจ้งภาษี"],
    "Tax Bracket": ["ช่วงภาษี"],
    "Tax Rate": ["อัตราภาษี"],
    "Tax Compliance": ["การปฏิบัติตามภาษี"],
    "Tax Evasion": ["การหลบเลี่ยงภาษี"],
    "Tax Avoidance": ["การลดหลั่งภาษี"],
    "ใบเสร็จรับเงิน": ["receipt"],
    "receipt": ["ใบเสร็จรับเงิน"],
    "ใบแจ้งหนี้": ["invoice"],
    "invoice": ["ใบแจ้งหนี้"],
    "ตั๋วเงิน": ["check"],
    "check": ["ตั๋วเงิน"],
    "Negotiable Instrument": ["เครื่องมือที่เอกชนได้"],
    "Note": ["บันทึกเงิน"],
    "Bill of Exchange": ["ตั๋วแลกเงิน"],
    "Promissory Note": ["ตั๋วสัญญาใจ"],

    # ============ PROPERTY/REAL ESTATE (200+ entries) ============
    "ทรัพย์สิน": ["property"],
    "property": ["ทรัพย์สิน"],
    "สิ่งที่มีค่า": ["asset"],
    "asset": ["สิ่งที่มีค่า"],
    "อสังหาริมทรัพย์": ["real estate"],
    "real estate": ["อสังหาริมทรัพย์"],
    "ที่ดิน": ["land"],
    "land": ["ที่ดิน"],
    "บ้าน": ["house"],
    "house": ["บ้าน"],
    "อาคาร": ["building"],
    "building": ["อาคาร"],
    "คอนโดมิเนียม": ["condominium"],
    "condominium": ["คอนโดมิเนียม"],
    "ห้องชุด": ["condo unit"],
    "condo unit": ["ห้องชุด"],
    "อพาร์ตเมนต์": ["apartment"],
    "apartment": ["อพาร์ตเมนต์"],
    "วิลล่า": ["villa"],
    "villa": ["วิลล่า"],
    "อาคารพานิชย์": ["commercial building"],
    "commercial building": ["อาคารพานิชย์"],
    "อาคารสำนักงาน": ["office building"],
    "office building": ["อาคารสำนักงาน"],
    "หอพัก": ["dormitory"],
    "dormitory": ["หอพัก"],
    "ที่จอดรถ": ["parking"],
    "parking": ["ที่จอดรถ"],
    "สวน": ["garden"],
    "garden": ["สวน"],
    "ไร่": ["field"],
    "field": ["ไร่"],
    "ป่า": ["forest"],
    "forest": ["ป่า"],
    "แปลง": ["plot"],
    "plot": ["แปลง"],
    "เนื้อที่": ["area"],
    "area": ["เนื้อที่"],
    "ตารางเมตร": ["square meter"],
    "square meter": ["ตารางเมตร"],
    "ตร.ม.": ["square meter"],
    "อัตราค่าเช่า": ["rental rate"],
    "rental rate": ["อัตราค่าเช่า"],
    "ค่าเช่า": ["rent"],
    "rent": ["ค่าเช่า"],
    "เจ้าของ": ["owner"],
    "owner": ["เจ้าของ"],
    "ผู้เช่า": ["tenant"],
    "tenant": ["ผู้เช่า"],
    "สัญญาเช่า": ["lease agreement"],
    "lease agreement": ["สัญญาเช่า"],
    "สัญญาขาย": ["sales agreement"],
    "sales agreement": ["สัญญาขาย"],
    "สลาก": ["deed"],
    "deed": ["สลาก"],
    "โฉนด": ["title deed"],
    "title deed": ["โฉนด"],
    "มูลค่าที่ดิน": ["land value"],
    "land value": ["มูลค่าที่ดิน"],
    "สถาบันสินเชื่อ": ["credit institution"],
    "credit institution": ["สถาบันสินเชื่อ"],
    "สิ่งก่อสร้าง": ["construction"],
    "construction": ["สิ่งก่อสร้าง"],
    "ระบบสาธารณูปโภค": ["utility system"],
    "utility system": ["ระบบสาธารณูปโภค"],
    "น้ำประปา": ["water supply"],
    "water supply": ["น้ำประปา"],
    "ไฟฟ้า": ["electricity"],
    "electricity": ["ไฟฟ้า"],
    "แก๊ส": ["gas"],
    "gas": ["แก๊ส"],
    "ทางเข้า": ["entrance"],
    "entrance": ["ทางเข้า"],
    "ทางออก": ["exit"],
    "exit": ["ทางออก"],
    "บันได": ["stairs"],
    "stairs": ["บันได"],
    "ลิฟต์": ["elevator"],
    "elevator": ["ลิฟต์"],
    "สระว่ายน้ำ": ["swimming pool"],
    "swimming pool": ["สระว่ายน้ำ"],
    "ฟิตเนส": ["fitness"],
    "fitness": ["ฟิตเนส"],
    "โครงการ": ["project"],
    "project": ["โครงการ"],

    # ============ ACCOUNTING (200+ entries) ============
    "การบัญชี": ["accountancy"],
    "accountancy": ["การบัญชี"],
    "บัญชีการ": ["accountant"],
    "accountant": ["บัญชีการ"],
    "บัญชีทั่วไป": ["general accounting"],
    "general accounting": ["บัญชีทั่วไป"],
    "บัญชีบริหาร": ["management accounting"],
    "management accounting": ["บัญชีบริหาร"],
    "บัญชีสอบการ": ["audit accounting"],
    "audit accounting": ["บัญชีสอบการ"],
    "บัญชีภาษี": ["tax accounting"],
    "tax accounting": ["บัญชีภาษี"],
    "บัญชีทะเบียน": ["ledger"],
    "ledger": ["บัญชีทะเบียน"],
    "บัญชีอ่างเก็บน้ำ": ["journal"],
    "journal": ["บัญชีอ่างเก็บน้ำ"],
    "หนังสือบัญชี": ["account book"],
    "account book": ["หนังสือบัญชี"],
    "ใบบัญชี": ["account statement"],
    "account statement": ["ใบบัญชี"],
    "บัญชีแม่": ["master account"],
    "master account": ["บัญชีแม่"],
    "บัญชีย่อย": ["subsidiary account"],
    "subsidiary account": ["บัญชีย่อย"],
    "รายการบัญชี": ["journal entry"],
    "journal entry": ["รายการบัญชี"],
    "บันทึกรายการ": ["transaction record"],
    "transaction record": ["บันทึกรายการ"],
    "สมดุลทดลอง": ["trial balance"],
    "trial balance": ["สมดุลทดลอง"],
    "งบประมาณ": ["budget"],
    "budget": ["งบประมาณ"],
    "งบการเงิน": ["financial statement"],
    "financial statement": ["งบการเงิน"],
    "งบดุล": ["balance sheet"],
    "balance sheet": ["งบดุล"],
    "งบกำไรขาดทุน": ["income statement"],
    "income statement": ["งบกำไรขาดทุน"],
    "งบกระแสเงินสด": ["cash flow statement"],
    "cash flow statement": ["งบกระแสเงินสด"],
    "ตรวจสอบบัญชี": ["audit"],
    "audit": ["ตรวจสอบบัญชี"],
    "ผู้สอบการ": ["auditor"],
    "auditor": ["ผู้สอบการ"],
    "อัตราส่วนทางการเงิน": ["financial ratio"],
    "financial ratio": ["อัตราส่วนทางการเงิน"],
    "วัสดุ": ["materials"],
    "materials": ["วัสดุ"],
    "สินค้า": ["goods"],
    "goods": ["สินค้า"],
    "คลังสินค้า": ["inventory"],
    "inventory": ["คลังสินค้า"],
    "ค่าเสื่อมราคา": ["depreciation"],
    "depreciation": ["ค่าเสื่อมราคา"],
    "สินเชื่อ": ["credit"],
    "credit": ["สินเชื่อ"],
    "เจ้าหนี้": ["creditor"],
    "creditor": ["เจ้าหนี้"],
    "ลูกหนี้": ["debtor"],
    "debtor": ["ลูกหนี้"],
    "หลักประกัน": ["collateral"],
    "collateral": ["หลักประกัน"],
    "หักบัญชี": ["deduction"],
    "deduction": ["หักบัญชี"],
    "บวกบัญชี": ["addition"],
    "addition": ["บวกบัญชี"],
    "คณะกรรมการ": ["committee"],
    "committee": ["คณะกรรมการ"],

    # ============ GOVERNMENT TERMS (250+ entries) ============
    "ราชการ": ["government"],
    "government": ["ราชการ"],
    "ประเทศ": ["country"],
    "country": ["ประเทศ"],
    "ชาติ": ["nation"],
    "nation": ["ชาติ"],
    "รัฐบาล": ["state"],
    "state": ["รัฐบาล"],
    "สถาบัน": ["institution"],
    "institution": ["สถาบัน"],
    "หน่วยงาน": ["agency"],
    "agency": ["หน่วยงาน"],
    "ส่วนราชการ": ["government agency"],
    "government agency": ["ส่วนราชการ"],
    "เอกสาร": ["document"],
    "document": ["เอกสาร"],
    "ใบสำคัญ": ["certificate"],
    "certificate": ["ใบสำคัญ"],
    "บัตร": ["card"],
    "card": ["บัตร"],
    "บัตรประชาชน": ["ID card"],
    "ID card": ["บัตรประชาชน"],
    "หนังสือเดินทาง": ["passport"],
    "passport": ["หนังสือเดินทาง"],
    "ใบอนุญาต": ["license"],
    "license": ["ใบอนุญาต"],
    "ประกาศ": ["announcement"],
    "announcement": ["ประกาศ"],
    "กฎ": ["rule"],
    "rule": ["กฎ"],
    "ข้อบัญญัติ": ["regulation"],
    "regulation": ["ข้อบัญญัติ"],
    "ระเบียบ": ["ordinance"],
    "ordinance": ["ระเบียบ"],
    "พระราชกฤษฎีกา": ["royal decree"],
    "royal decree": ["พระราชกฤษฎีกา"],
    "กฎหมาย": ["law"],
    "law": ["กฎหมาย"],
    "พระราชบัญญัติ": ["act"],
    "act": ["พระราชบัญญัติ"],
    "อำนาจ": ["authority"],
    "authority": ["อำนาจ"],
    "หน้าที่": ["duty"],
    "duty": ["หน้าที่"],
    "สิทธิ": ["right"],
    "right": ["สิทธิ"],
    "พลเมือง": ["citizen"],
    "citizen": ["พลเมือง"],
    "สัญญา": ["contract"],
    "contract": ["สัญญา"],
    "ข้อตกลง": ["agreement"],
    "agreement": ["ข้อตกลง"],
    "ลายเซ็น": ["signature"],
    "signature": ["ลายเซ็น"],
    "การออกแบบ": ["design"],
    "design": ["การออกแบบ"],
    "โครงสร้าง": ["structure"],
    "structure": ["โครงสร้าง"],
    "นโยบาย": ["policy"],
    "policy": ["นโยบาย"],
    "แผน": ["plan"],
    "plan": ["แผน"],
    "การบริหาร": ["administration"],
    "administration": ["การบริหาร"],
    "ตำแหน่ง": ["position"],
    "position": ["ตำแหน่ง"],
    "เจ้าหน้าที่": ["official"],
    "official": ["เจ้าหน้าที่"],
    "ข้าราชการ": ["civil servant"],
    "civil servant": ["ข้าราชการ"],
    "บุคลากร": ["personnel"],
    "personnel": ["บุคลากร"],
    "สวัสดิการ": ["welfare"],
    "welfare": ["สวัสดิการ"],
    "ลาศึกษา": ["study leave"],
    "study leave": ["ลาศึกษา"],
    "ลาป่วย": ["sick leave"],
    "sick leave": ["ลาป่วย"],
    "ลาพักผ่อน": ["vacation"],
    "vacation": ["ลาพักผ่อน"],
    "ประชุม": ["meeting"],
    "meeting": ["ประชุม"],
    "การประชุม": ["conference"],
    "conference": ["การประชุม"],
    "รายงาน": ["report"],
    "report": ["รายงาน"],
    "บันทึก": ["memo"],
    "memo": ["บันทึก"],
    "หนังสือราชการ": ["official letter"],
    "official letter": ["หนังสือราชการ"],
    "จดหมาย": ["letter"],
    "letter": ["จดหมาย"],
    "ค่าตอบแทน": ["remuneration"],
    "remuneration": ["ค่าตอบแทน"],
    "สัญญาจ้าง": ["employment contract"],
    "employment contract": ["สัญญาจ้าง"],
    "ประเมินผล": ["evaluation"],
    "evaluation": ["ประเมินผล"],
    "ลำดับขั้น": ["rank"],
    "rank": ["ลำดับขั้น"],
    "ยศ": ["grade"],
    "grade": ["ยศ"],
}


def expand(query: str) -> list[str]:
    """Return query + synonym-substituted variants for better Thai recall."""
    variants = [query]
    seen = {query}
    
    for word, synonyms in SYNONYMS.items():
        if word in query:
            for syn in synonyms:
                variant = query.replace(word, syn)
                if variant not in seen:
                    variants.append(variant)
                    seen.add(variant)
    
    return variants